name: Hobbio  # Change this line to your desired new name

description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.6
  file_picker: ^6.2.0
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.7
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  http: ^1.2.1
  image_picker: ^1.0.7
  progress_dialog_null_safe: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/karate1.jpg
    - assets/karate2.jpg
    - assets/pro.jpg
  fonts:
    - family: Hobbio
      fonts:
        - asset: assets/fonts/HappyLucky-gxnZP.ttf
    - family: Hobbio2
      fonts:
        - asset: assets/fonts/MondayFeelings-7BD2l.ttf
    - family: Hobbio3
      fonts:
        - asset: assets/fonts/SummaryNotesRegular-Ea5ln.ttf
    - family: Hobbio4
      fonts:
        - asset: assets/fonts/LuckySunshine-axo9R.ttf
    - family: Hobbio5
      fonts:
        - asset: assets/fonts/BabySela-vmxz4.ttf
    - family: Hobbio6
      fonts:
        - asset: assets/fonts/BetterGrade-519DV.ttf
    - family: Hobbio7
      fonts:
        - asset: assets/fonts/BrettleySignatureRegular-RpEMo.ttf
    - family: Hobbio8
      fonts:
        - asset: assets/fonts/TiltNeon[XROT,YROT].ttf
